name: Telegram Bot Notification

on:
  # Manual trigger with environment input
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

  schedule:
    - cron: '00 00 * * *'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Determine environment
        id: determine-env
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "env=production" >> "$GITHUB_OUTPUT"
          else
            echo "env=${{ github.event.inputs.environment }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Set CHAT_ID output
        id: set-chat-id
        run: |
          if [[ "${{ steps.determine-env.outputs.env }}" == "production" ]]; then
            echo "chat_id=${{ secrets.PROD_CHAT_ID }}" >> "$GITHUB_OUTPUT"
          else
            echo "chat_id=${{ secrets.STAGING_CHAT_ID }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Show CHAT_ID for debug
        run: echo "Using CHAT_ID=${{ steps.set-chat-id.outputs.chat_id }}"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest tests --disable-warnings --maxfail=1

      - name: Restore cached jobs.db
        uses: actions/cache@v4
        with:
          path: jobs.db
          key: jobs-db-${{ steps.determine-env.outputs.env }}

      - name: Trigger telegram bot
        run: python main.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          CHAT_ID: ${{ steps.set-chat-id.outputs.chat_id }}

      - name: Save updated jobs.db to cache
        uses: actions/cache@v4
        with:
          path: jobs.db
          key: jobs-db-${{ steps.determine-env.outputs.env }}-${{ github.run_id }}
          restore-keys: |
            jobs-db-${{ steps.determine-env.outputs.env }}
